*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 2022.07.25 at 16:57:49
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZOBSV_CONFIG....................................*
FORM GET_DATA_ZOBSV_CONFIG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZOBS_CONFIG WHERE
(VIM_WHERETAB) .
    CLEAR ZOBSV_CONFIG .
ZOBSV_CONFIG-MANDT =
ZOBS_CONFIG-MANDT .
ZOBSV_CONFIG-SYSID =
ZOBS_CONFIG-SYSID .
ZOBSV_CONFIG-BUCKET =
ZOBS_CONFIG-BUCKET .
ZOBSV_CONFIG-ACTIVE =
ZOBS_CONFIG-ACTIVE .
ZOBSV_CONFIG-OBSAK =
ZOBS_CONFIG-OBSAK .
ZOBSV_CONFIG-OBSSK =
ZOBS_CONFIG-OBSSK .
ZOBSV_CONFIG-HOST =
ZOBS_CONFIG-HOST .
ZOBSV_CONFIG-LOGLIFE =
ZOBS_CONFIG-LOGLIFE .
ZOBSV_CONFIG-PSIZE =
ZOBS_CONFIG-PSIZE .
ZOBSV_CONFIG-AUTOCLEAR =
ZOBS_CONFIG-AUTOCLEAR .
ZOBSV_CONFIG-CLEARDATE =
ZOBS_CONFIG-CLEARDATE .
ZOBSV_CONFIG-ERNAM =
ZOBS_CONFIG-ERNAM .
ZOBSV_CONFIG-ERDAT =
ZOBS_CONFIG-ERDAT .
ZOBSV_CONFIG-ERZET =
ZOBS_CONFIG-ERZET .
ZOBSV_CONFIG-AENAM =
ZOBS_CONFIG-AENAM .
ZOBSV_CONFIG-AEDAT =
ZOBS_CONFIG-AEDAT .
ZOBSV_CONFIG-AEZET =
ZOBS_CONFIG-AEZET .
<VIM_TOTAL_STRUC> = ZOBSV_CONFIG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZOBSV_CONFIG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZOBSV_CONFIG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZOBSV_CONFIG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZOBS_CONFIG WHERE
  SYSID = ZOBSV_CONFIG-SYSID AND
  BUCKET = ZOBSV_CONFIG-BUCKET .
    IF SY-SUBRC = 0.
    DELETE ZOBS_CONFIG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZOBS_CONFIG WHERE
  SYSID = ZOBSV_CONFIG-SYSID AND
  BUCKET = ZOBSV_CONFIG-BUCKET .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZOBS_CONFIG.
    ENDIF.
ZOBS_CONFIG-MANDT =
ZOBSV_CONFIG-MANDT .
ZOBS_CONFIG-SYSID =
ZOBSV_CONFIG-SYSID .
ZOBS_CONFIG-BUCKET =
ZOBSV_CONFIG-BUCKET .
ZOBS_CONFIG-ACTIVE =
ZOBSV_CONFIG-ACTIVE .
ZOBS_CONFIG-OBSAK =
ZOBSV_CONFIG-OBSAK .
ZOBS_CONFIG-OBSSK =
ZOBSV_CONFIG-OBSSK .
ZOBS_CONFIG-HOST =
ZOBSV_CONFIG-HOST .
ZOBS_CONFIG-LOGLIFE =
ZOBSV_CONFIG-LOGLIFE .
ZOBS_CONFIG-PSIZE =
ZOBSV_CONFIG-PSIZE .
ZOBS_CONFIG-AUTOCLEAR =
ZOBSV_CONFIG-AUTOCLEAR .
ZOBS_CONFIG-CLEARDATE =
ZOBSV_CONFIG-CLEARDATE .
ZOBS_CONFIG-ERNAM =
ZOBSV_CONFIG-ERNAM .
ZOBS_CONFIG-ERDAT =
ZOBSV_CONFIG-ERDAT .
ZOBS_CONFIG-ERZET =
ZOBSV_CONFIG-ERZET .
ZOBS_CONFIG-AENAM =
ZOBSV_CONFIG-AENAM .
ZOBS_CONFIG-AEDAT =
ZOBSV_CONFIG-AEDAT .
ZOBS_CONFIG-AEZET =
ZOBSV_CONFIG-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZOBS_CONFIG ##WARN_OK.
    ELSE.
    INSERT ZOBS_CONFIG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZOBSV_CONFIG-UPD_FLAG,
STATUS_ZOBSV_CONFIG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZOBSV_CONFIG.
  SELECT SINGLE * FROM ZOBS_CONFIG WHERE
SYSID = ZOBSV_CONFIG-SYSID AND
BUCKET = ZOBSV_CONFIG-BUCKET .
ZOBSV_CONFIG-MANDT =
ZOBS_CONFIG-MANDT .
ZOBSV_CONFIG-SYSID =
ZOBS_CONFIG-SYSID .
ZOBSV_CONFIG-BUCKET =
ZOBS_CONFIG-BUCKET .
ZOBSV_CONFIG-ACTIVE =
ZOBS_CONFIG-ACTIVE .
ZOBSV_CONFIG-OBSAK =
ZOBS_CONFIG-OBSAK .
ZOBSV_CONFIG-OBSSK =
ZOBS_CONFIG-OBSSK .
ZOBSV_CONFIG-HOST =
ZOBS_CONFIG-HOST .
ZOBSV_CONFIG-LOGLIFE =
ZOBS_CONFIG-LOGLIFE .
ZOBSV_CONFIG-PSIZE =
ZOBS_CONFIG-PSIZE .
ZOBSV_CONFIG-AUTOCLEAR =
ZOBS_CONFIG-AUTOCLEAR .
ZOBSV_CONFIG-CLEARDATE =
ZOBS_CONFIG-CLEARDATE .
ZOBSV_CONFIG-ERNAM =
ZOBS_CONFIG-ERNAM .
ZOBSV_CONFIG-ERDAT =
ZOBS_CONFIG-ERDAT .
ZOBSV_CONFIG-ERZET =
ZOBS_CONFIG-ERZET .
ZOBSV_CONFIG-AENAM =
ZOBS_CONFIG-AENAM .
ZOBSV_CONFIG-AEDAT =
ZOBS_CONFIG-AEDAT .
ZOBSV_CONFIG-AEZET =
ZOBS_CONFIG-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZOBSV_CONFIG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZOBSV_CONFIG-SYSID TO
ZOBS_CONFIG-SYSID .
MOVE ZOBSV_CONFIG-BUCKET TO
ZOBS_CONFIG-BUCKET .
MOVE ZOBSV_CONFIG-MANDT TO
ZOBS_CONFIG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZOBS_CONFIG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZOBS_CONFIG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZOBS_CONFIG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
